### ISSUE TITLE
metal LB does not support configmaps anymore

### ISSUE THREAD

**Issue by rs38** [danrg/raspberry-pi-kubernetes#1]
workaround
  create a  file metallb_specs.yaml                                          

```
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: my-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.0.240-192.168.0.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2-advertisement
  namespace: metallb-system
```
and apply it
`kubectl apply -f metallb_specs.yaml`

https://metallb.io/configuration/migration_to_crds/index.html
